Update karate.yml
Apply same change to back end go

diff --git a/.github/workflows/karate.yml b/.github/workflows/karate.yml
--- a/.github/workflows/karate.yml
+++ b/.github/workflows/karate.yml
@@ -4,14 +4,102 @@ on:
   schedule:
     # Run the ci on the latest commit of master every day at 4:00 am
     - cron:  '00 04 * * *'
-
-  pull_request:
-    types:
-      - opened
-      - synchronize
-      - reopened
       
-jobs:
+jobs:    
+  be1-go:
+    name: Be1-Go
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Use go >= 1.19
+        uses: actions/setup-go@v3
+        with:
+          go-version: ">=1.19"
+
+      - name: Setup repo
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - uses: actions/cache@v3
+        with:
+          # In order:
+          # * Module download cache
+          # * Build cache (Linux)
+          path: |
+            ~/go/pkg/mod
+            ~/.cache/go-build
+          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+          restore-keys: |
+            ${{ runner.os }}-go-
+      
+      - name: Build
+        working-directory: ./be1-go
+        run: |
+          make build
+        
+      - name: Run Karate tests
+        id: tests
+        continue-on-error: true
+        working-directory: ./tests/karate
+        run: mvn test -DargLine=-Dkarate.env=go -Dtest=BackEndTest#fullTest
+        
+      - name: Publish HTML Report
+        uses: actions/upload-artifact@v3
+        with:
+          name: Go HTML Report
+          path: ./tests/karate/target/karate-reports
+                  
+      - name: Publish Cucumber Report
+        uses: actions/upload-artifact@v3
+        with:
+          name: Go Cucumber Report
+          path: ./tests/karate/target/cucumber-html-reports
+          
+      - name: Publish Server logs
+        uses: actions/upload-artifact@v3
+        with:
+          name: Go Server Logs
+          path: ./tests/karate/go.log
+          
+      # The next actions are pushing the new report to the defined branch
+      - name: Checkout report branch
+        uses: actions/checkout@v3
+        with:
+          ref: report-karate-be1-go
+          path: report-repo
+      
+      - name: Update report
+        if: ${{ always() }} # execute even if previous steps failed
+        run: |
+          rm -rf report-repo/*
+          cp -a ./tests/karate/target/cucumber-html-reports/. ./report-repo/
+          
+      - name: Get current date
+        if: ${{ always() }} # execute even if previous steps failed
+        id: date
+        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
+        
+      - name: Commit files
+        working-directory: ./report-repo
+        run: |
+          git config --local user.email "github-actions[bot]@users.noreply.github.com"
+          git config --local user.name "github-actions[bot]"
+          git add -A
+          git commit -m "Report from ${{ steps.date.outputs.date }}"
+          
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: report-karate-be1-go
+          directory: report-repo
+      
+      - name: Fail job if the tests were not successful
+        # Catchup of tests failure such that the job fo fail
+        if: steps.tests.outcome == 'failure'
+        run: exit 1
+        
   be2-scala:
     name: Be2-Scala
     runs-on: ubuntu-latest
@@ -87,101 +175,7 @@ jobs:
           branch: report-karate-be2-scala
           directory: report-repo
           
-      - name: Fail job if the test were not successful
+      - name: Fail job if the tests were not successful
         # Catchup of tests failure such that the job fo fail
         if: steps.tests.outcome == 'failure'
         run: exit 1
-          
-  be1-go:
-    name: Be1-Go
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Use go >= 1.19
-        uses: actions/setup-go@v3
-        with:
-          go-version: ">=1.19"
-
-      - name: Setup repo
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-
-      - uses: actions/cache@v3
-        with:
-          # In order:
-          # * Module download cache
-          # * Build cache (Linux)
-          path: |
-            ~/go/pkg/mod
-            ~/.cache/go-build
-          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-          restore-keys: |
-            ${{ runner.os }}-go-
-      
-      - name: Build
-        if: ${{ always() }} # execute even if previous steps failed
-        working-directory: ./be1-go
-        run: |
-          make build
-        
-      - name: Run Karate tests
-        working-directory: ./tests/karate
-        run: mvn test -DargLine=-Dkarate.env=go -Dtest=BackEndTest#fullTest
-        
-      - name: Publish HTML Report
-        if: ${{ always() }} # execute even if previous steps failed
-        uses: actions/upload-artifact@v3
-        with:
-          name: Go HTML Report
-          path: ./tests/karate/target/karate-reports
-                  
-      - name: Publish Cucumber Report
-        if: ${{ always() }} # execute even if previous steps failed
-        uses: actions/upload-artifact@v3
-        with:
-          name: Go Cucumber Report
-          path: ./tests/karate/target/cucumber-html-reports
-          
-      - name: Publish Server logs
-        if: ${{ always() }} # execute even if previous steps failed
-        uses: actions/upload-artifact@v3
-        with:
-          name: Go Server Logs
-          path: ./tests/karate/go.log
-          
-      # The next actions are pushing the new report to the defined branch
-      - name: Checkout report branch
-        if: ${{ always() }} # execute even if previous steps failed
-        uses: actions/checkout@v3
-        with:
-          ref: report-karate-be1-go
-          path: report-repo
-      
-      - name: Update report
-        if: ${{ always() }} # execute even if previous steps failed
-        run: |
-          rm -rf report-repo/*
-          cp -a ./tests/karate/target/cucumber-html-reports/. ./report-repo/
-          
-      - name: Get current date
-        if: ${{ always() }} # execute even if previous steps failed
-        id: date
-        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
-        
-      - name: Commit files
-        if: ${{ always() }} # execute even if previous steps failed
-        working-directory: ./report-repo
-        run: |
-          git config --local user.email "github-actions[bot]@users.noreply.github.com"
-          git config --local user.name "github-actions[bot]"
-          git add -A
-          git commit -m "Report from ${{ steps.date.outputs.date }}"
-          
-      - name: Push changes
-        if: ${{ always() }} # execute even if previous steps failed
-        uses: ad-m/github-push-action@master
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          branch: report-karate-be1-go
-          directory: report-repo
